import type { Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { clerkModalAppearance } from "@/lib/clerk-modal-appearance";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <ClerkProvider appearance={clerkModalAppearance}>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
